apiVersion: v1
kind: Service
metadata:
  name: {{ include "cellcast.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cellcast.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
    {{- if gt (int .Values.ports.metrics) 0 }}
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "cellcast.selectorLabels" . | nindent 4 }}
